markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Chris Benninger
production_url : http://benninger.ca
description: "Code, rants, utilities, tutorials, projects and other things by Chris Benninger."
disqus_shortname: benningerca
analytics: UA-5453717-1
author :
  name : Chris Benninger
  github : cbenning
  twitter : chrisbenninger
